### ISSUE TITLE
No MacosWindowScope found in content 🐛 

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#155]
**Description**

When manually toggling the sidebar using `MacosWindowScope.of(context).toggleSidebar()`, I get the following error: 

```
No MacosWindowScope found in context
'package:macos_ui/src/layout/window.dart':
Failed assertion: line 287 pos 12: 'result != null'
```

**Steps To Reproduce**

1. Clone and run the [macosui_counter](https://github.com/GroovinChip/macosui_counter) example
2. Click on the 'toggle sidebar' icon button
3. Observe the error 

**Expected behavior**

The sidebar should appear/disappear on button click

**Screenshots**

N/A

**Logs**

<details>
  <summary>Logs</summary>

```
No MacosWindowScope found in context
'package:macos_ui/src/layout/window.dart':
Failed assertion: line 287 pos 12: 'result != null'

When the exception was thrown, this was the stack: 
#2      MacosWindowScope.of (package:macos_ui/src/layout/window.dart:287:12)
#3      _DesktopCounterState.build.<anonymous closure> (package:macosui_counter/ui/screens/desktop_counter.dart:42:49)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:525:8)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#24     _invoke1 (dart:ui/hooks.dart:185:10)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#4639b
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(666.9, 37.1)
  finalLocalPosition: Offset(17.9, 29.1)
  button: 1
  sent tap down
====================================================================================================

```

</details>

**Comment by GroovinChip** [comment]
@lesliearkorful can you take a look at this please

**Comment by GroovinChip** [comment]
per @lesliearkorful , I wrapped `MacosScaffold` in a `Builder` and this does the trick. The docs should be updated to mention that this is required.

**Comment by GroovinChip** [comment]
Resolved
