### ISSUE TITLE
MacosPopupMenuItem - Unhandled Exception

### ISSUE THREAD

**Issue by stanislavlysenko0912** [macosui/macos_ui#297]
Using of MacosPopupMenuItem drop exception on click to open. 
If skip the error, the menu opens anyway.

![изображение](https://user-images.githubusercontent.com/86171768/186788672-7f71e4a0-90a6-4488-b4be-db237613f7da.png)

<details>
<summary>Exception</summary>

```
Restarted application in 337ms.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 151 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      ScrollController.animateTo
#3      _MacosPopupMenuItemButtonState._handleFocusChange
#4      _FocusState._handleFocusChanged
#5      ChangeNotifier.notifyListeners
#6      FocusNode._notify
#7      FocusManager._applyFocusChange
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

</details>

<details>
<summary>Code</summary>

```
CupertinoTabView(
      builder: (_) => MacosScaffold(
        children: [
          ContentArea(
            builder: (context, scrollController) {
              return SizedBox(
                height: 40,
                width: 200,
                child: MacosPopupButton(
                  value: 'One',
                  onChanged: (String? newValue) {},
                  items: <String>['One', 'Two', 'Three', 'Four'].map<MacosPopupMenuItem<String>>((String value) {
                    return MacosPopupMenuItem<String>(
                      value: value,
                      child: Text(value),
                    );
                  }).toList(),
                ),
              );
            },
          ),
        ],
      ),
    ),
```
</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2432, on macOS 12.2.1 21D62
    darwin-arm, locale en-UA)
    • Flutter version 3.1.0-0.0.pre.2432 on channel master at
      /Users/stanislavlysenko/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8027842393 (2 days ago), 2022-08-23 09:32:39 -0700
    • Engine revision c9d0a01281
    • Dart version 2.19.0 (build 2.19.0-127.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/stanislavlysenko/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by GroovinChip** [comment]
Thanks for filing this bug, @stanislavlysenko0912. A fix is incoming.
