### ISSUE TITLE
SideBar background color is completely dark when running with Light theme

### ISSUE THREAD

**Issue by ricard-v** [macosui/macos_ui#319]
**Description**

When running the Flutter app in light theme with this package, the `SideBar` background color is broken as it is completely dark.

Also, there is no issue whatsoever in dark theme.

**Steps To Reproduce**
I was able to reproduce the issue with the example code from this repository.

1. Run the example project with `macos_ui: ^1.7.5`

**Expected behavior**

In light theme, the `SideBar` should not be dark. Instead it should have that grey-ish pale white color that contrasts with the pure white background of main content area.

**Screenshots**

This is my Mac:
![image](https://user-images.githubusercontent.com/1658248/202698560-62b0d72f-6de2-4b6a-8c01-7e7bd5a789e3.png)

_in light theme_
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/1658248/202702552-ce044454-119f-43a5-882b-3197aaf7076d.png">

_in dark theme_
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1658248/202702749-076c7dbd-0616-4223-97cb-92de86e1a656.png">

**Logs**

<details>
  <summary>Logs</summary>

```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-0004693E22FA401E }
{ platform:macOS, arch:x86_64, id:00006000-0004693E22FA401E }
Debug service listening on ws://127.0.0.1:58822/n8EcYFfH8AY=/ws
Syncing files to device macOS...

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1597:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1622:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1551:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1597:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1622:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1551:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1597:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1622:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1551:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1597:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1622:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1551:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================

```

```
XXXXX@Mxxxx example % flutter analyze
Analyzing example...                                                    

   info • The value of the local variable 'appTheme' isn't used • lib/main.dart:28:15 • unused_local_variable

1 issue found. (ran in 1.3s)
```

```
XXXXX@Mxxxx Runner % flutter doctor -v
[✓] Flutter (Channel master, 3.6.0-5.0.pre.13, on macOS 12.6.1 21G217 darwin-arm64, locale fr-FR)
    • Flutter version 3.6.0-5.0.pre.13 on channel master at /Users/XXXXX/workspace/others/flutter-sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8a7102e7ed (12 hours ago), 2022-11-17 16:08:46 -0500
    • Engine revision d955a72c56
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/p994624/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = ~/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is xxxxxxxx
    ! NO_PROXY does not contain localhost
    • NO_PROXY contains 127.0.0.1
    ! NO_PROXY does not contain ::1

[✓] Connected device (4 available)
    • SM N970F (mobile)       • R58M903CJQW                              • android-arm64  • Android 10 (API 29)
    • iPhone 6S Plus (mobile) • 5d5150ae4098e734e249769b08cc9fc66c9d21aa • ios            • iOS 15.7 19H12
    • macOS (desktop)         • macos                                    • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by ricard-v** [comment]
Issue is solved. I was building the project against flutter master channel. Sorry for submitting this issue!

**Comment by alexrabin** [comment]
I am having this issue on latest stable version 3.7.0

Edit:

I had to manually set the flutterViewController background color to clear and then it worked:

```swift
flutterViewController.backgroundColor = .clear
```

**Comment by nonacosa** [comment]
> I am having this issue on latest stable version 3.7.0
> 
> Edit:
> 
> I had to manually set the flutterViewController background color to white and then it worked:
> 
> ```swift
> flutterViewController.backgroundColor = .clear
> ```

I have same issue on flutter 3.7.0 , It work for me, Thanks you  ❤
