### ISSUE TITLE
Window Translucency Effect not working

### ISSUE THREAD

**Issue by Chandram-Dutta** [macosui/macos_ui#332]
**Description**

The window translucency effect does not work and shows a black background, this occurred after updating flutter to 3.7.0. It was working fine before

**Steps To Reproduce**

<details>
The mason build macosui_starter app has the issue.

</details>

**Expected behavior**
The macOS translucency effect should work like any other macOS app

**Screenshots**
<img width="912" alt="Screenshot 2023-01-27 at 12 02 58 AM" src="https://user-images.githubusercontent.com/81961406/214922039-f9bfcc9d-c732-4d48-a996-7b1d3d7bb074.png">

**Logs**

<details>
  <summary>Logs</summary>

```
flutter run
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008112-000C24493CF1401E }
{ platform:macOS, arch:x86_64, id:00008112-000C24493CF1401E }
warning: invalid character in Bundle Identifier. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters. (in target 'Runner' from project 'Runner')
Building macOS application...                                           
Syncing files to device macOS...                                    41ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:55169/gVlAfYRXK-c=/

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.
A Scrollbar cannot be painted without a ScrollPosition.
The Scrollbar attempted to use the provided ScrollController. This ScrollController should be
associated with the ScrollView that the Scrollbar is being applied to.When providing your own
ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack:
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1597:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1622:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1551:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942:7)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: The Scrollbar's ScrollController has no ScrollPosition attached.
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:55169/gVlAfYRXK-c=/

Another exception was thrown: The Scrollbar's ScrollController has no ScrollPosition attached.
Application finished.

```

```
flutter analyze
Analyzing macosui_starter...                                            

   info • 'body' is deprecated and shouldn't be used. Use the child attribute instead. This feature was deprecated after v3.1.0-0.0.pre • lib/main.dart:130:7
          • deprecated_member_use

1 issue found. (ran in 1.4s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.2 22D49 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0 on channel stable at /Users/chandramdutta/Developer/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (3 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/chandramdutta/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/chandramdutta/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/chandramdutta/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by GroovinChip** [comment]
Yes, I'm encountering this as well and am investigating. So far no luck.

**Comment by damywise** [comment]
@GroovinChip 
https://github.com/Adrian-Samoticha/macos_window_utils.dart/issues/12
https://github.com/leanflutter/window_manager/issues/293
https://github.com/flutter/flutter/issues/119132

**Comment by GroovinChip** [comment]
@damywise thank you for linking related issues and the solution. I'll update the README shortly to include it.
